### ISSUE TITLE
GC overhead limit exceeded BEAST

### ISSUE THREAD

**Issue by Chase-Brownstein** [Chase-Brownstein/finalproject#1]
Issue with combining trees in TreeAnnotator and LogCombiner. Unfortunately I have a new macbook and so I'm not sure how to work to change this issue with java's garbage collector on this device. Following code appears as is standard in TreeAnnotator: 
Processing 7501 trees from file after ignoring first 25% = 2500 trees.
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.StringBuilder.toString(StringBuilder.java:407)
	at org.antlr.v4.runtime.RuleContext.getText(RuleContext.java:140)
	at org.antlr.v4.runtime.RuleContext.getText(RuleContext.java:137)
	at org.antlr.v4.runtime.RuleContext.getText(RuleContext.java:137)
	at beast.util.TreeParser$NewickASTVisitor.processMetadata(Unknown Source)
	at beast.util.TreeParser$NewickASTVisitor.visitNode(Unknown Source)
	at beast.util.TreeParser$NewickASTVisitor.visitNode(Unknown Source)
	at beast.util.treeparser.NewickParser$NodeContext.accept(Unknown Source)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at beast.util.TreeParser$NewickASTVisitor.visitNode(Unknown Source)
	at beast.util.TreeParser$NewickASTVisitor.visitNode(Unknown Source)
	at beast.util.treeparser.NewickParser$NodeContext.accept(Unknown Source)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at beast.util.TreeParser$NewickASTVisitor.visitNode(Unknown Source)
	at beast.util.TreeParser$NewickASTVisitor.visitNode(Unknown Source)
	at beast.util.treeparser.NewickParser$NodeContext.accept(Unknown Source)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at beast.util.TreeParser$NewickASTVisitor.visitNode(Unknown Source)
	at beast.util.TreeParser$NewickASTVisitor.visitNode(Unknown Source)
	at beast.util.treeparser.NewickParser$NodeContext.accept(Unknown Source)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at beast.util.TreeParser$NewickASTVisitor.visitNode(Unknown Source)
	at beast.util.TreeParser$NewickASTVisitor.visitNode(Unknown Source)
	at beast.util.treeparser.NewickParser$NodeContext.accept(Unknown Source)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at beast.util.TreeParser$NewickASTVisitor.visitNode(Unknown Source)
	at beast.util.TreeParser$NewickASTVisitor.visitNode(Unknown Source)
	at beast.util.treeparser.NewickParser$NodeContext.accept(Unknown Source)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at beast.util.TreeParser$NewickASTVisitor.visitNode(Unknown Source)

Secondly, I just want to report that mixing for the posterior probabilities is still fairly poor for over 10 million generations in each example. I'm sure this has to do with the large # of priors and am not particularly concerned about this given that we are mainly concerned with simply how the calibration lists generally affect divergence dates. I did want to raise this issue though. Thank you!

**Comment by Chase-Brownstein** [comment]
UPDATE: I was able to figure out *part* of the problem, which is the need to increase java's memory on my computer. I'm currently trying to increase heap size using-Xms in the Java control center.

**Comment by Chase-Brownstein** [comment]
Resolved!
